# Generated by Django 3.0.3 on 2020-02-09 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_auto_20200209_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.Categoria'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='date',
            field=models.DateField(),
        ),
    ]
